akexorcist/ruam-mij-android

README.md
เพิ่ม guideline เบื้องต้นสำหรับนักพัฒนาที่อยาก build app จาก source code โดยตรง
=> nit: add guideline for building apk from source

README.md, app/src/main/java/com/akexorcist/ruammij/data/DeviceRepository.kt, app/src/main/java/com/akexorcist/ruammij/di/AppModule.kt, app/src/main/java/com/akexorcist/ruammij/ui/accessibility/AccessibilityScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/accessibility/AccessibilityViewModel.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppViewModel.kt, app/src/main/java/com/akexorcist/ruammij/ui/overview/OverviewScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/overview/OverviewViewModel.kt
Solve issue
- Cache app results in DeviceRepository.
- Optimize ViewModel to fetch data in parallel.
- Use Kotlin sequences to optimize multiple map parts in getRunningMediaProjectionApps.
=> feat: cache apps result in repository and fetch data in parallel

.github/workflows/ci.yml
- add base CI for verify the PR
- Run Build & Test for now
=> feat: Add Github CI

app/src/main/java/com/akexorcist/ruammij/MainActivity.kt, app/src/main/java/com/akexorcist/ruammij/SharedEventViewModel.kt, app/src/main/java/com/akexorcist/ruammij/common/Contributors.kt, app/src/main/java/com/akexorcist/ruammij/common/Installers.kt, app/src/main/java/com/akexorcist/ruammij/data/DeviceRepository.kt, app/src/main/java/com/akexorcist/ruammij/data/InstalledApp.kt, app/src/main/java/com/akexorcist/ruammij/ui/aboutapp/AboutAppScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/accessibility/AccessibilityScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/component/AppInfo.kt, app/src/main/java/com/akexorcist/ruammij/ui/component/Installer.kt, app/src/main/java/com/akexorcist/ruammij/ui/component/LanguageDropdownButton.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppViewModel.kt, app/src/main/java/com/akexorcist/ruammij/ui/overview/OverviewScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/overview/OverviewViewModel.kt, app/src/main/java/com/akexorcist/ruammij/utility/PackageManager.kt, app/src/main/res/values-th/strings.xml, app/src/main/res/values/strings.xml
* Mapping installer app name from installed app informations
* Rename "Preload or ADB" to "OS or ADB"
* Change format of mapping installer list
* Add more installer
* Move contributors list to `Contributors`
=> refactor: add installer app name when possible

.github/workflows/release.yml, app/build.gradle.kts
Decrypted keystore from GitHub Secrets for release build
=> feat: add keystore in release workflow

app/build.gradle.kts
Use project direction + keystore path from env
=> fix: incorrect keystore path

.github/workflows/release.yml, app/build.gradle.kts
no need to use keystore path since it's just a file path
=> fix: change keystore path

.github/workflows/release.yml
https://github.com/softprops/action-gh-release/issues/236
=> fix: add content permission

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, app/build.gradle.kts, app/src/main/java/com/akexorcist/ruammij/common/Contributors.kt, app/src/main/java/com/akexorcist/ruammij/common/Installers.kt, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
=> Add "ASUS System Update Service" to verified installers

README.md, app/build.gradle.kts, app/src/main/java/com/akexorcist/ruammij/RuamMijApplication.kt, app/src/main/java/com/akexorcist/ruammij/common/Contributors.kt, app/src/main/java/com/akexorcist/ruammij/data/DeviceRepository.kt, app/src/main/java/com/akexorcist/ruammij/data/database/RuamMijDatabase.kt, app/src/main/java/com/akexorcist/ruammij/data/database/SafeApp.kt, app/src/main/java/com/akexorcist/ruammij/data/database/SafeAppDao.kt, app/src/main/java/com/akexorcist/ruammij/di/AppModule.kt, app/src/main/java/com/akexorcist/ruammij/di/DatabaseModule.kt, app/src/main/java/com/akexorcist/ruammij/ui/accessibility/AccessibilityScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/component/AppInfo.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppViewModel.kt, app/src/main/res/values-th/strings.xml, app/src/main/res/values/strings.xml, build.gradle.kts, gradle/libs.versions.toml
=> feat: mask warning/danger installed app as safe

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/akexorcist/ruammij/ui/aboutapp/AboutAppScreen.kt, build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
test with emulator
https://github.com/akexorcist/ruam-mij-android/assets/17794661/1bb0d35f-f84b-4e5d-8f17-e40b8120c33c
test with real device
https://github.com/akexorcist/ruam-mij-android/assets/17794661/9c6ddf87-0805-4cf3-a323-b0582c579998
=> feat: add open source license

README.md, app/src/main/java/com/akexorcist/ruammij/common/Contributors.kt
Add these names in contributor list
* Monthira Chayabanjonglerd
* Kittinun Vantasin
=> Add more contributors

.github/workflows/release.yml
ทำให้ release job สามารถสร้าง pull request ได้ ด้วยการเพิ่ม permission เข้าไปใน job นั้น
=> fix: add pull request permission for release job

.all-contributorsrc, README.md
closes #31
@akexorcist Can you follow steps 1 and 2 from this [page](https://allcontributors.org/docs/en/bot/installation#1-install-the-allcontributors-github-app) to set up all-contributors.
This PR is step 3 of the page. I added a badge to the top of the README as well.
=> chore: add contributors section to readme

.github/workflows/snapshot_test.yml, app/build.gradle.kts
To support Gradle update action, it requires to use Java 11 in project
=> feat: use java 11

README.md, app/src/main/java/com/akexorcist/ruammij/common/Contributors.kt, app/src/main/java/com/akexorcist/ruammij/ui/aboutapp/AboutAppScreen.kt
Add
* Pitsanu Kittipittayakorn
* Pun Butrach
* Siriwat Kunaporn
* Nayuki
=> feat: update contributor list

app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
After removing open source licenses menu from the app
=> Remove OSS license plugin

.github/workflows/bump-version.yml, .github/workflows/release.yml
* Bump version action
* Release app action
=> Change bump version and release workflow

app/build.gradle.kts, app/src/main/java/com/akexorcist/ruammij/ui/BottomMenu.kt, app/src/main/java/com/akexorcist/ruammij/ui/Navigation.kt, app/src/main/java/com/akexorcist/ruammij/ui/RuamMijApp.kt, app/src/main/java/com/akexorcist/ruammij/ui/aboutapp/AboutAppNavigation.kt, app/src/main/java/com/akexorcist/ruammij/ui/accessibility/AccessibilityNavigation.kt, app/src/main/java/com/akexorcist/ruammij/ui/installedapp/InstalledAppNavigation.kt, app/src/main/java/com/akexorcist/ruammij/ui/osslicense/OpenSourceLicenseNavigation.kt, app/src/main/java/com/akexorcist/ruammij/ui/overview/OverviewNavigation.kt, gradle/libs.versions.toml
Use serializable data instead of plain string
=> feat: migrate new navigation compose implementation

app/src/main/java/com/akexorcist/ruammij/ui/aboutapp/AboutAppScreen.kt, app/src/main/java/com/akexorcist/ruammij/ui/component/AppInfoBottomSheet.kt
=> fix: incorrect modal bottom sheet top padding
